import os
import django
from applikacja.models import Books

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "biblioteka1.settings")
django.setup()



books_data = [
    {
        "author": "F. Scott Fitzgerald",
        "title": "The Great Gatsby",
        "time_period_of_creation": 1925,
        "language": "english",
        "publication_year": 1925,
        "publisher": "Charles Scribner's Sons",
        "description": "The Great Gatsby is a novel by F. Scott Fitzgerald that depicts the decline and decay of the American Dream in the Jazz Age. It is considered one of the greatest works of American literature.",
        "genre": "common_literature",

    },
    {
        "author": "Gabriel Garcia Marquez",
        "title": "One Hundred Years of Solitude",
        "time_period_of_creation": 1967,
        "language": "english",
        "publication_year": 1967,
        "publisher": "Harper & Row",
        "description": "One Hundred Years of Solitude is a landmark novel by Colombian author Gabriel Garcia Marquez. It tells the story of the Buendia family across seven generations, blending elements of magical realism with political commentary and social criticism.",
        "genre": "foreign_belles_lettres",

    },
{
        "author": "Henryk Sienkiewicz",
        "title": "Ogniem i mieczem",
        "time_period_of_creation": 1884,
        "language": "polish",
        "publication_year": 1884,
        "publisher": "Gebethner i Wolff",
        "description": "Ogniem i mieczem to powieść historyczna autorstwa Henryka Sienkiewicza, osadzona w realiach XVII-wiecznej Rzeczypospolitej. Opowiada o wydarzeniach związanych z powstaniem Chmielnickiego.",
        "genre": "common_literature",

    },
    {
        "author": "Bolesław Prus",
        "title": "Lalka",
        "time_period_of_creation": 1890,
        "language": "polish",
        "publication_year": 1890,
        "publisher": "Książka",
        "description": "Lalka to powieść realistyczna autorstwa Bolesława Prusa, ukazująca życie warszawskiej elity w drugiej połowie XIX wieku. Opowiada historię Stanisława Wokulskiego, który marzy o wzbogaceniu się i zdobyciu serca pięknej Izabeli Łęckiej.",
        "genre": "common_literature",

    },
    {
        "author": "Stanisław Lem",
        "title": "Solaris",
        "time_period_of_creation": 1961,
        "language": "polish",
        "publication_year": 1961,
        "publisher": "Czytelnik",
        "description": "Solaris to powieść science fiction autorstwa Stanisława Lema. Akcja rozgrywa się na tajemniczej planecie Solaris, na której występują dziwne zjawiska i istoty pozaziemskie. Książka porusza tematykę ludzkiej natury, komunikacji i poznawania nieznanego.",
        "genre": "science_fiction",

    },
    {
        "author": "Stefan Żeromski",
        "title": "Ludzie bezdomni",
        "time_period_of_creation": 1899,
        "language": "polish",
        "publication_year": 1899,
        "publisher": "Gebethner i Wolff",
        "description": "Ludzie bezdomni to powieść społeczno-psychologiczna autorstwa Stefana Żeromskiego, która ukazuje losy bezdomnych i wykluczonych społecznie ludzi w okresie przełomu XIX i XX wieku.",
        "genre": "common_literature",

    },
    {
        "author": "Wisława Szymborska",
        "title": "Widok z ziarnkiem piasku",
        "time_period_of_creation": 1996,
        "language": "polish",
        "publication_year": 1996,
        "publisher": "Znak",
        "description": "Widok z ziarnkiem piasku to zbiór wierszy nagrodzony Nagrodą Nobla w dziedzinie literatury w 1996 roku. Książka zawiera poetyckie refleksje autorki na temat egzystencji, miłości, czasu i przemijania.",
        "genre": "poezja",

    },
    {
        "author": "Wiesław Myśliwski",
        "title": "Traktat o łuskaniu fasoli",
        "time_period_of_creation": 2006,
        "language": "polish",
        "publication_year": 2006,
        "publisher": "Wydawnictwo Literackie",
        "description": "Traktat o łuskaniu fasoli to powieść Wiesława Myśliwskiego, która zdobyła Nagrodę Nike w 2007 roku. Książka opowiada historię chłopca z małej wsi, który staje się świadkiem dramatycznych wydarzeń w czasie II wojny światowej.",
        "genre": "common_literature",

    },
    {
        "author": "Magdalena Tulli",
        "title": "Służby porządkowe",
        "time_period_of_creation": 2003,
        "language": "polish",
        "publication_year": 2003,
        "publisher": "Wydawnictwo Literackie",
        "description": "Służby porządkowe to powieść Magdaleny Tulli, która otrzymała Nagrodę Nike w 2003 roku. Książka jest eksperymentalną formą literacką, łączącą elementy prozy, eseju i poezji, i porusza tematykę przemijania i transformacji.",
        "genre": "common_literature",

    },
    {
        "author": "Janusz Leon Wiśniewski",
        "title": "Ferdydurke",
        "time_period_of_creation": 1937,
        "language": "polish",
        "publication_year": 1937,
        "publisher": "Rój",
        "description": "Ferdydurke to powieść autorstwa Witolda Gombrowicza, która jest jednym z najważniejszych dzieł polskiej literatury XX wieku. Książka jest satyrą na społeczeństwo i edukację, oraz eksploruje tematy takie jak tożsamość, dorastanie i alienację.",
        "genre": "common_literature",
    },
    {
        "author": "Olga Tokarczuk",
        "title": "Bieguni",
        "time_period_of_creation": 2007,
        "language": "polish",
        "publication_year": 2007,
        "publisher": "Wydawnictwo Literackie",
        "description": "Bieguni to powieść Olgi Tokarczuk, która otrzymała Nagrodę Nike w 2008 roku. Książka porusza tematykę podróży, ruchu i poszukiwania tożsamości, eksplorując różne wymiary ludzkiego istnienia.",
        "genre": "common_literature",
    },
    {
        "author": "Tadeusz Dołęga-Mostowicz",
        "title": "Kariera Nikodema Dyzmy",
        "time_period_of_creation": 1932,
        "language": "polish",
        "publication_year": 1932,
        "publisher": "Nasza Księgarnia",
        "description": "Kariera Nikodema Dyzmy to powieść satyryczna autorstwa Tadeusza Dołęgi-Mostowicza. Książka opowiada historię Nikodema Dyzmy, który dzięki manipulacjom i intrygom zdobywa wpływowe stanowisko społeczne.",
        "genre": "common_literature",

    },
    {
        "author": "Gustaw Herling-Grudziński",
        "title": "Inny świat",
        "time_period_of_creation": 1951,
        "language": "polish",
        "publication_year": 1951,
        "publisher": "PIW",
        "description": "Inny świat to powieść autobiograficzna Gustawa Herlinga-Grudzińskiego, w której autor opisuje swoje doświadczenia jako więzień sowieckiego łagru w czasie II wojny światowej.",
        "genre": "reportage",

    },
    {
        "author": "Walter Isaacson",
        "title": "Steve Jobs",
        "time_period_of_creation": 2011,
        "language": "english",
        "publication_year": 2011,
        "publisher": "Simon & Schuster",
        "description": "Steve Jobs is a biography of Apple co-founder Steve Jobs written by Walter Isaacson. The book provides an in-depth look into the life and career of Steve Jobs, his innovative ideas, and his impact on the technology industry.",
        "genre": "biografy",

    },
    {
        "author": "Michelle Obama",
        "title": "Becoming",
        "time_period_of_creation": 2018,
        "language": "english",
        "publication_year": 2018,
        "publisher": "Crown Publishing Group",
        "description": "Becoming is a memoir by former First Lady Michelle Obama. The book chronicles her life, from her childhood in Chicago to her years in the White House, and shares her personal experiences, insights, and reflections.",
        "genre": "biografy",

    },
    {
        "author": "Malala Yousafzai",
        "title": "I Am Malala",
        "time_period_of_creation": 2013,
        "language": "english",
        "publication_year": 2013,
        "publisher": "Little, Brown and Company",
        "description": "I Am Malala is an autobiography of Malala Yousafzai, a Pakistani activist for female education and the youngest Nobel Prize laureate. The book tells the story of her life, including her advocacy for girls' education and the assassination attempt on her.",
        "genre": "biografy",

    },
    {
        "author": "Nelson Mandela",
        "title": "Long Walk to Freedom",
        "time_period_of_creation": 1994,
        "language": "english",
        "publication_year": 1994,
        "publisher": "Little, Brown and Company",
        "description": "Long Walk to Freedom is an autobiography of Nelson Mandela, the South African anti-apartheid revolutionary and political leader. The book traces Mandela's life journey, including his activism, imprisonment, and eventual presidency.",
        "genre": "biografy",

    },
    {
        "author": "Walter Isaacson",
        "title": "Leonardo da Vinci",
        "time_period_of_creation": 2017,
        "language": "english",
        "publication_year": 2017,
        "publisher": "Simon & Schuster",
        "description": "Leonardo da Vinci is a biography of the renowned Italian artist and inventor written by Walter Isaacson. The book delves into da Vinci's life, explores his artistic and scientific endeavors, and sheds light on his genius and creativity.",
        "genre": "biografy",

    },
    {
        "author": "Stephen King",
        "title": "The Shining",
        "time_period_of_creation": 1977,
        "language": "english",
        "publication_year": 1977,
        "publisher": "1977",
        "description": "The Shining is a horror novel by Stephen King. The story follows Jack Torrance, a writer and recovering alcoholic, who becomes the winter caretaker of the isolated Overlook Hotel. As the winter progresses, supernatural forces in the hotel begin to influence Jack's sanity.",
        "genre": "horror",

    },
    {
        "author": "Shirley Jackson",
        "title": "The Haunting of Hill House",
        "time_period_of_creation": 1959,
        "language": "english",
        "publication_year": 1959,
        "publisher": "Viking Press",
        "description": "The Haunting of Hill House is a horror novel by Shirley Jackson. The book tells the story of four individuals who stay at Hill House to participate in a paranormal study, but they soon experience terrifying supernatural occurrences that haunt them.",
        "genre": "horror",

    },
    {
        "author": "H.P. Lovecraft",
        "title": "At the Mountains of Madness",
        "time_period_of_creation": 1931,
        "language": "english",
        "publication_year": 1931,
        "publisher": "Astounding Stories",
        "description": "At the Mountains of Madness is a horror novella by H.P. Lovecraft. The story follows an Antarctic expedition that uncovers ancient and otherworldly horrors in the icy mountains, leading to madness and destruction.",
        "genre": "horror",

    },
    {
        "author": "Clive Barker",
        "title": "Hellbound Heart",
        "time_period_of_creation": 1986,
        "language": "english",
        "publication_year": 1986,
        "publisher": "Dark Harvest",
        "description": "Hellbound Heart is a horror novella by Clive Barker. The story revolves around a puzzle box called the Lemarchand's Box, which opens a gateway to a dimension inhabited by sadomasochistic beings known as the Cenobites.",
        "genre": "horror",

    },
    {
        "author": "Edgar Allan Poe",
        "title": "The Tell-Tale Heart",
        "time_period_of_creation": 1843,
        "language": "english",
        "publication_year": 1843,
        "publisher": "The Pioneer",
        "description": "The Tell-Tale Heart is a short story by Edgar Allan Poe. The narrator, plagued by guilt, confesses his crime of murdering an old man and reveals the haunting madness that leads to his own downfall.",
        "genre": "horror",

    },
    {
        "author": "Julia Donaldson",
        "title": "Gruffalo",
        "time_period_of_creation": 1999,
        "language": "polish",
        "publication_year": 1999,
        "publisher": "Nasza Księgarnia",
        "description": "Gruffalo to opowieść o małym myszku, który w drodze przez las spotyka różne zwierzęta i udaje się uniknąć niebezpieczeństwa dzięki swojej sprytnej inwencji.",
        "genre": "child",

    },
    {
        "author": "Kornel Makuszyński",
        "title": "Awantury i wybryki małej małpki Fiki-Miki",
        "time_period_of_creation": 1930,
        "language": "polish",
        "publication_year": 1930,
        "publisher": "Nasza Księgarnia",
        "description": "Awantury i wybryki małej małpki Fiki-Miki to zbiór opowiadań o perypetiach sympatycznej małpki, która wpada w różne zabawne i kłopotliwe sytuacje.",
        "genre": "child",

    },
    {
        "author": "Renata Piątkowska",
        "title": "Wierszyki dla dzieci",
        "time_period_of_creation": 2005,
        "language": "polish",
        "publication_year": 2005,
        "publisher": "Media Rodzina",
        "description": "Wierszyki dla dzieci to zbiór krótkich wierszyków i rymowanek, które bawią i uczą najmłodszych czytelników.",
        "genre": "child",

    },
    {
        "author": "Maria Kownacka",
        "title": "O dwóch takich, co ukradli księżyc",
        "time_period_of_creation": 1956,
        "language": "polish",
        "publication_year": 1956,
        "publisher": "Nasza Księgarnia",
        "description": "O dwóch takich, co ukradli księżyc to historia dwóch sprytnych chłopców, Janka i Ancyka, którzy postanawiają ukraść księżyc, aby spełnić marzenia swojej chorej siostry.",
        "genre": "child",

    },
    {
        "author": "Joanna Papuzińska",
        "title": "Złote myśli",
        "time_period_of_creation": 2015,
        "language": "polish",
        "publication_year": 2015,
        "publisher": "Media Rodzina",
        "description": "Złote myśli to zbiór mądrych i pełnych wartości opowiadań, które uczą dzieci ważnych lekcji życiowych i pomagają rozwijać wyobraźnię.",
        "genre": "child",

    },
    {
        "author": "Olga Tokarczuk",
        "title": "Prowadź swój pług przez kości umarłych",
        "time_period_of_creation": 2009,
        "language": "polish",
        "publication_year": 2009,
        "publisher": "Wydawnictwo Literackie",
        "description": "Prowadź swój pług przez kości umarłych to powieść kryminalna z elementami nadprzyrodzonymi. Główna bohaterka, Janina Duszejko, prowadzi dochodzenie w sprawie tajemniczych morderstw w małej wiosce.",
        "genre": "literature",

    },
    {
        "author": "Erik Larson",
        "title": "The Devil in the White City",
        "time_period_of_creation": 2003,
        "language": "english",
        "publication_year": 2003,
        "publisher": "Vintage",
        "description": "The Devil in the White City tells the story of the 1893 World's Fair in Chicago and the serial killer H.H. Holmes who used the fair as a hunting ground.",
        "genre": "literature",

    },

    {
        "author": "Henryk Sienkiewicz",
        "title": "Quo Vadis",
        "time_period_of_creation": 1895,
        "language": "polish",
        "publication_year": 1895,
        "publisher": "Gebethner i Wolff",
        "description": "Quo Vadis is a historical novel by Henryk Sienkiewicz. It takes place in ancient Rome and tells the story of a love affair between a Roman patrician and a Christian woman amidst the backdrop of Nero's persecution of Christians.",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "Stefan Żeromski",
        "title": "Popioły",
        "time_period_of_creation": 1904,
        "language": "polish",
        "publication_year": 1904,
        "publisher": "Nakładem Autora",
        "description": "Popioły is a novel by Stefan Żeromski. It tells the story of Włodzimierz, a Polish nobleman who becomes disillusioned with the ideals of his class and joins the January Uprising, a Polish national revolt against the Russian Empire.",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "Czesław Miłosz",
        "title": "Zniewolony umysł",
        "time_period_of_creation": 1953,
        "language": "polish",
        "publication_year": 1953,
        "publisher": "Instytut Literacki",
        "description": "Zniewolony umysł is a collection of poems by Czesław Miłosz. It explores themes of captivity, oppression, and the struggle for freedom.",
        "genre": "poezja",

    },
    {
        "author": "Zbigniew Herbert",
        "title": "Pan Cogito",
        "time_period_of_creation": 1974,
        "language": "polish",
        "publication_year": 1974,
        "publisher": "Wydawnictwo Literackie",
        "description": "Pan Cogito is a collection of poems by Zbigniew Herbert. The poems delve into philosophical themes and examine the human condition.",
        "genre": "poezja",

    },
    {
        "author": "Eliza Orzeszkowa",
        "title": "Nad Niemnem",
        "time_period_of_creation": 1888,
        "language": "polish",
        "publication_year": 1888,
        "publisher": "Księgarnia Gubrynowicza i Schmidta",
        "description": "Nad Niemnem is a novel by Eliza Orzeszkowa. It tells the story of a noble family living on the banks of the Neman River and explores themes of love, tradition, and social change.",
        "genre": "romans",

    },
    {
        "author": "Bolesław Prus",
        "title": "Emancypantki",
        "time_period_of_creation": 1893,
        "language": "polish",
        "publication_year": 1893,
        "publisher": "Nakład Gebethnera i Wolffa",
        "description": "Emancypantki is a novel by Bolesław Prus. It focuses on the lives of three young women from the Polish intelligentsia and examines the role of women in society.",
        "genre": "romans",

    },
    {
        "author": "Stanisław Wyspiański",
        "title": "Wesele",
        "time_period_of_creation": 1901,
        "language": "polish",
        "publication_year": 1901,
        "publisher": "Nakład Gebethnera i Wolffa",
        "description": "Wesele is a play by Stanisław Wyspiański, considered one of the greatest works of Polish drama. It portrays the wedding ceremony of a young couple and explores themes of Polish society, national identity, and the clash between tradition and modernity.",
        "genre": "common_literature",

    },
    {
        "author": "Henryk Sienkiewicz",
        "title": "Krzyżacy",
        "time_period_of_creation": 1900,
        "language": "polish",
        "publication_year": 1900,
        "publisher": "Wydawnictwo Literackie",
        "description": "Krzyżacy is a historical novel by Henryk Sienkiewicz, set in the 15th-century Teutonic Order's conflict with Poland and Lithuania. It follows the story of a young Polish knight who joins the war against the Teutonic Knights and faces personal and moral challenges.",
        "genre": "common_literature",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Kamień Filozoficzny",
        "time_period_of_creation": 1997,
        "language": "polish",
        "publication_year": 1997,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Kamień Filozoficzny (Harry Potter and the Philosopher's Stone) is the first book in the Harry Potter series by J.K. Rowling. It follows the story of Harry Potter, a young wizard, as he begins his magical education at Hogwarts School of Witchcraft and Wizardry.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Komnata Tajemnic",
        "time_period_of_creation": 1998,
        "language": "polish",
        "publication_year": 1998,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Komnata Tajemnic (Harry Potter and the Chamber of Secrets) is the second book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's second year at Hogwarts School of Witchcraft and Wizardry, as he investigates the mystery of the Chamber of Secrets.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Więzień Azkabanu",
        "time_period_of_creation": 1999,
        "language": "polish",
        "publication_year": 1999,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Więzień Azkabanu (Harry Potter and the Prisoner of Azkaban) is the third book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's third year at Hogwarts School of Witchcraft and Wizardry, as he encounters the dangerous escaped prisoner Sirius Black.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Czara Ognia",
        "time_period_of_creation": 2000,
        "language": "polish",
        "publication_year": 2000,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Czara Ognia (Harry Potter and the Goblet of Fire) is the fourth book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's fourth year at Hogwarts School of Witchcraft and Wizardry, as he participates in the Triwizard Tournament and faces the return of Lord Voldemort.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Zakon Feniksa",
        "time_period_of_creation": 2003,
        "language": "polish",
        "publication_year": 2003,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Zakon Feniksa (Harry Potter and the Order of the Phoenix) is the fifth book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's fifth year at Hogwarts School of Witchcraft and Wizardry, as he faces challenges from the newly formed Ministry of Magic and forms a secret organization called the Order of the Phoenix.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Książę Półkrwi",
        "time_period_of_creation": 2005,
        "language": "polish",
        "publication_year": 2005,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Książę Półkrwi (Harry Potter and the Half-Blood Prince) is the sixth book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's sixth year at Hogwarts School of Witchcraft and Wizardry, as he learns more about Lord Voldemort's past and prepares for the final battle.",
        "genre": "child",

    },
    {
        "author": "J.K. Rowling",
        "title": "Harry Potter i Insygnia Śmierci",
        "time_period_of_creation": 2007,
        "language": "polish",
        "publication_year": 2007,
        "publisher": "Media Rodzina",
        "description": "Harry Potter i Insygnia Śmierci (Harry Potter and the Deathly Hallows) is the seventh and final book in the Harry Potter series by J.K. Rowling. It follows Harry Potter's final year at Hogwarts School of Witchcraft and Wizardry, as he and his friends embark on a dangerous quest to destroy the Horcruxes and defeat Lord Voldemort.",
        "genre": "child",

    },
    {
        "author": "Suzanne Collins",
        "title": "The Hunger Games",
        "time_period_of_creation": 2008,
        "language": "english",
        "publication_year": 2008,
        "publisher": "Scholastic",
        "description": "The Hunger Games is a dystopian novel set in a post-apocalyptic world where teenagers from different districts are forced to participate in a televised fight to the death.",
        "genre": "child",

    },
    {
        "author": "Suzanne Collins",
        "title": "Catching Fire",
        "time_period_of_creation": 2009,
        "language": "english",
        "publication_year": 2009,
        "publisher": "Scholastic",
        "description": "Catching Fire is the second book in the Hunger Games trilogy, continuing the story of Katniss Everdeen as she becomes a symbol of rebellion against the oppressive Capitol.",
        "genre": "child",

    },
    {
        "author": "Suzanne Collins",
        "title": "Mockingjay",
        "time_period_of_creation": 2010,
        "language": "english",
        "publication_year": 2010,
        "publisher": "Scholastic",
        "description": "Mockingjay is the final book in the Hunger Games trilogy, following the rebellion against the Capitol and the ultimate fate of Katniss Everdeen.",
        "genre": "child",

    },
    {
        "author": "Jane Austen",
        "title": "Rozważna i romantyczna",
        "time_period_of_creation": 1811,
        "language": "polish",
        "publication_year": 1811,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",
    },
    {
        "author": "Charlotte Brontë",
        "title": "Dziwne losy Jane Eyre",
        "time_period_of_creation": 1847,
        "language": "polish",
        "publication_year": 1847,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "Jane Austen",
        "title": "Opactwo Northanger",
        "time_period_of_creation": 1817,
        "language": "polish",
        "publication_year": 1817,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "Jane Austen",
        "title": "Perswazje",
        "time_period_of_creation": 1818,
        "language": "polish",
        "publication_year": 1818,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "D.H. Lawrence",
        "title": "Kochanek Lady Chatterley",
        "time_period_of_creation": 1928,
        "language": "polish",
        "publication_year": 1928,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "Alexandre Dumas (syn)",
        "title": "Dama Kameliowa",
        "time_period_of_creation": 1848,
        "language": "polish",
        "publication_year": 1848,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "George Eliot (pseudonim dla Mary Anne Evans)",
        "title": "Młyn nad Flossą",
        "time_period_of_creation": 1860,
        "language": "polish",
        "publication_year": 1860,
        "publisher": "",
        "description": "",
        "genre": "polish_belles_lettres",

    },
    {
        "author": "George Orwell",
        "title": "1984",
        "time_period_of_creation": 1949,
        "language": "english",
        "publication_year": 1949,
        "publisher": "Secker & Warburg",
        "description": "1984 is a dystopian novel set in a totalitarian society where individualism and independent thinking are suppressed.",
        "genre": "common_literature",

    },
    {
        "author": "Lewis Carroll",
        "title": "Alicja w Krainie Czarów",
        "time_period_of_creation": 1865,
        "language": "polish",
        "publication_year": 1865,
        "publisher": "Macmillan",
        "description": "Alicja w Krainie Czarów is a fantasy novel about a young girl named Alice who falls through a rabbit hole into a whimsical world.",
        "genre": "child",

    },
    {
        "author": "Lucy Maud Montgomery",
        "title": "Ania z Zielonego Wzgórza",
        "time_period_of_creation": 1908,
        "language": "polish",
        "publication_year": 1908,
        "publisher": "L.C. Page & Co.",
        "description": "Ania z Zielonego Wzgórza is a coming-of-age novel about a spirited orphan girl named Anne Shirley who goes to live with the Cuthbert siblings on Prince Edward Island.",
        "genre": "child",

    },
    {
        "author": "David Mitchell",
        "title": "Atlas chmur",
        "time_period_of_creation": 2004,
        "language": "polish",
        "publication_year": 2004,
        "publisher": "Hodder & Stoughton",
        "description": "Atlas chmur is a novel that weaves together six interconnected stories spanning different time periods and locations, exploring themes of reincarnation and interconnectedness.",
        "genre": "common_literature",

    },
    {
        "author": "Agnieszka Stelmaszyk",
        "title": "Baśń o trzech braciach",
        "time_period_of_creation": 2016,
        "language": "polish",
        "publication_year": 2016,
        "publisher": "Nasza Księgarnia",
        "description": "Baśń o trzech braciach is a fairy tale about three brothers who embark on a magical journey to save their kingdom from an evil sorcerer.",
        "genre": "child",

    },
    {
        "author": "Viktor E. Frankl",
        "title": "Człowiek w poszukiwaniu sensu",
        "time_period_of_creation": 1946,
        "language": "polish",
        "publication_year": 1946,
        "publisher": "Beacon Press",
        "description": "Człowiek w poszukiwaniu sensu is a memoir and psychological exploration by Viktor E. Frankl, a Holocaust survivor, that explores the importance of finding meaning in life.",
        "genre": "common_literature",

    },
    {
        "author": "Frank Herbert",
        "title": "Diuna",
        "time_period_of_creation": 1965,
        "language": "english",
        "publication_year": 1965,
        "publisher": "Chilton Books",
        "description": "Diuna is a science fiction novel set in a distant future where interstellar travel and political intrigue revolve around the desert planet Arrakis and its valuable resource known as 'spice'.",
        "genre": "common_literature",

    },
    {
        "author": "Bram Stoker",
        "title": "Dracula",
        "time_period_of_creation": 1897,
        "language": "english",
        "publication_year": 1897,
        "publisher": "Archibald Constable and Company",
        "description": "Dracula is an epistolary novel that follows the vampire Count Dracula as he attempts to move from Transylvania to England and spread the undead curse, while a group of people led by Professor Abraham Van Helsing tries to stop him.",
        "genre": "horror",

    },
    {
        "author": "Cormac McCarthy",
        "title": "Droga",
        "time_period_of_creation": 2006,
        "language": "english",
        "publication_year": 2006,
        "publisher": "Alfred A. Knopf",
        "description": "Droga is a post-apocalyptic novel that follows a father and his young son as they journey across a barren landscape in a desperate struggle to survive and find hope.",
        "genre": "common_literature",

    },
    {
        "author": "Knut Hamsun",
        "title": "Głód",
        "time_period_of_creation": 1890,
        "language": "norwegian",
        "publication_year": 1890,
        "publisher": "Gyldendalske Boghandels Forlag",
        "description": "Głód is a novel that delves into the mind of a struggling writer, exploring themes of hunger, poverty, and the human condition.",
        "genre": "common_literature",

    },
    {
    "author": "J.R.R. Tolkien",
    "title": "Hobbit, czyli tam i z powrotem",
    "time_period_of_creation": 1937,
    "language": "polish",
    "publication_year": 1937,
    "publisher": "Allen & Unwin",
    "description": "Hobbit, czyli tam i z powrotem is a fantasy novel that follows the adventures of Bilbo Baggins as he embarks on a quest to reclaim the Lonely Mountain and its treasure from the dragon Smaug.",
    "genre": "common_literature",

    },
    {
    "author": "Rudyard Kipling",
    "title": "Księga dżungli",
    "time_period_of_creation": 1894,
    "language": "polish",
    "publication_year": 1894,
    "publisher": "Macmillan Publishers",
    "description": "Księga dżungli is a collection of stories that depict the adventures of Mowgli, a boy raised by wolves in the Indian jungle, and his encounters with various animals and characters.",
    "genre": "common_literature",

    },
    {
    "author": "Guillermo del Toro, Cornelia Funke",
    "title": "Labirynt fauna",
    "time_period_of_creation": 2006,
    "language": "polish",
    "publication_year": 2006,
    "publisher": "Salamandra",
    "description": "Labirynt fauna is a dark fantasy novel that combines elements of fairy tales, horror, and historical fiction. It tells the story of a young girl named Ofelia who discovers a magical labyrinth during the Spanish Civil War.",
    "genre": "common_literature",

    },
    {
    "author": "Stephen King",
    "title": "Lśnienie",
    "time_period_of_creation": 1977,
    "language": "polish",
    "publication_year": 1977,
    "publisher": "Doubleday",
    "description": "Lśnienie is a horror novel that follows the story of Jack Torrance, a writer who becomes the winter caretaker at the isolated Overlook Hotel. As supernatural forces take hold, Jack's sanity unravels, and his son Danny has psychic abilities that unlock the hotel's dark secrets.",
    "genre": "horror",

    },
    {
    "author": "Antoine de Saint-Exupéry",
    "title": "Mały Książę",
    "time_period_of_creation": 1943,
    "language": "polish",
    "publication_year": 1943,
    "publisher": "Reynal & Hitchcock",
    "description": "Mały Książę is a philosophical novella that follows the encounters of a young prince as he travels from planet to planet, learning about life, love, and human nature. It explores themes of innocence, friendship, and the importance of seeing beyond the surface.",
    "genre": "child",

    },
    {
    "author": "Michaił Bułhakow",
    "title": "Mistrz i Małgorzata",
    "time_period_of_creation": 1940,
    "language": "polish",
    "publication_year": 1940,
    "publisher": "Moscow magazine",
    "description": "Mistrz i Małgorzata is a satirical novel that blends elements of fantasy and historical fiction. It follows the Devil's visit to Moscow and the chaos that ensues as he and his entourage meddle with the lives of the city's inhabitants.",
    "genre": "common_literature",

    },
    {
    "author": "Milan Kundera",
    "title": "Nieznośna lekkość bytu",
    "time_period_of_creation": 1984,
    "language": "polish",
    "publication_year": 1984,
    "publisher": "Grove Press",
    "description": "Nieznośna lekkość bytu is a philosophical novel that explores the themes of love, relationships, and the concept of eternal recurrence. It follows the interconnected lives of several characters in Prague during the Czechoslovak political upheavals of the 1960s and 1970s.",
    "genre": "common_literature",

    },
    {
    "author": "Jacek Dukaj",
    "title": "Odrodzenie",
    "time_period_of_creation": 1997,
    "language": "polish",
    "publication_year": 1997,
    "publisher": "SuperNOWA",
    "description": "Odrodzenie is a science fiction novel set in a future where nanotechnology has transformed society. It explores themes of artificial intelligence, post-humanism, and the impact of technology on humanity.",
    "genre": "common_literature",

    },
    {
    "author": "Andrzej Sapkowski",
    "title": "Ostatnie życzenie",
    "time_period_of_creation": 1993,
    "language": "polish",
    "publication_year": 1993,
    "publisher": "SuperNOWA",
    "description": "Ostatnie życzenie to książka fantasy, która wprowadza postać Geralta z Rivii - wiedźmina tropiącego potwory w świecie dręczonym przez nadnaturalne istoty. Książka składa się z serii opowiadań, które stanowią fundament sagi o Wiedźminie.",
    "genre": "fantasy",

    },
    {
    "author": "Stanisław Lem",
    "title": "Pamiętnik znaleziony w wannie",
    "time_period_of_creation": 1961,
    "language": "polish",
    "publication_year": 1961,
    "publisher": "Wydawnictwo Literackie",
    "description": "Pamiętnik znaleziony w wannie to powieść science fiction opowiadająca historię tajnej organizacji o nazwie 'Badania Metafizyczne i Epistemologiczne Wittgensteina', która bada dziwne zjawiska i naturę rzeczywistości.",
    "genre": "science_fiction",

    },
    {
    "author": "Terry Pratchett",
    "title": "Piękny buntownik",
    "time_period_of_creation": 1996,
    "language": "polish",
    "publication_year": 1996,
    "publisher": "Czwarta Strona",
    "description": "Piękny buntownik to powieść fantasy osadzona w świecie Dysku autorstwa Terry'ego Pratchetta. Opowiada o przygodach Moist von Lipwiga, oszusta, który zostaje zmuszony do przejęcia zrujnowanej poczty i przywrócenia jej do życia.",
    "genre": "fantasy",

    },
    {
    "author": "E.L. James",
    "title": "Pięćdziesiąt twarzy Greya",
    "time_period_of_creation": 2011,
    "language": "polish",
    "publication_year": 2011,
    "publisher": "Wielka Litera",
    "description": "Pięćdziesiąt twarzy Greya to erotyczna powieść romantyczna, która eksploruje relację pomiędzy Anastasią Steele i Christianem Greyem. Zyskała popularność ze względu na swoją eksplicitną treść i stała się bestsellerem.",
    "genre": "romans",

    },
    {
    "author": "Oscar Wilde",
    "title": "Portret Doriana Graya",
    "time_period_of_creation": 1890,
    "language": "polish",
    "publication_year": 1890,
    "publisher": "Lippincott's Monthly Magazine",
    "description": "Portret Doriana Graya to filozoficzna powieść opowiadająca historię młodego mężczyzny o imieniu Dorian Gray, który pozostaje wiecznie młody, podczas gdy jego portret starzeje się i odsłania jego moralne zepsucie.",
    "genre": "literatura obyczajowa",

    },
    {
    "author": "Stephen King",
    "title": "Sklepik z marzeniami",
    "time_period_of_creation": 1993,
    "language": "polish",
    "publication_year": 1993,
    "publisher": "Albatros",
    "description": "Sklepik z marzeniami to powieść grozy autorstwa Stephena Kinga. Opowiada historię Lelanda Gaunta, tajemniczego właściciela sklepu, który spełnia najskrytsze pragnienia ludzi, ale za wysoką cenę. Ukazuje pokusy, chciwość i mroczną stronę ludzkiej natury.",
    "genre": "horror",

    },
    {
    "author": "Milorad Pavić",
    "title": "Słownik Khazarski",
    "time_period_of_creation": 1984,
    "language": "polish",
    "publication_year": 1984,
    "publisher": "Wydawnictwo Literackie",
    "description": "Słownik Khazarski to niezwykła powieść słownikowa, która opowiada historię wymarłego ludu Khazarów. Książka jest podzielona na trzy części - chrześcijańską, muzułmańską i żydowską, oferując różne perspektywy na tę zaginioną cywilizację.",
    "genre": "literatura obyczajowa",

    },
    {
    "author": "Katarzyna Bondyra",
    "title": "Spotkanie nad morzem",
    "time_period_of_creation": 2020,
    "language": "polish",
    "publication_year": 2020,
    "publisher": "Wydawnictwo Otwarte",
    "description": "Spotkanie nad morzem to powieść obyczajowa, która opowiada historię dwóch osób, które przypadkowo spotykają się na plaży i spędzają razem kilka intensywnych dni. To opowieść o miłości, tęsknocie i odkrywaniu siebie nawzajem.",
    "genre": "literatura obyczajowa",

    },
    {
    "author": "Frances Hodgson Burnett",
    "title": "Tajemniczy ogród",
    "time_period_of_creation": 1911,
    "language": "polish",
    "publication_year": 1911,
    "publisher": "Oficyna Wydawnicza Alma-Press",
    "description": "Tajemniczy ogród to powieść dla dzieci, która opowiada historię Mary Lennox, sieroty, która odkrywa opuszczony ogród w posiadłości swojego wuja. To opowieść o przyjaźni, magii i odkrywaniu piękna natury.",
    "genre": "dla dzieci",

    },
    {
    "author": "Anton Czechow",
    "title": "Trzy siostry",
    "time_period_of_creation": 1901,
    "language": "polish",
    "publication_year": 1901,
    "publisher": "Wydawnictwo Poznańskie",
    "description": "Trzy siostry to sztuka teatralna, która opowiada historię trzech sióstr - Olgi, Maszy i Iriny - mieszkających w prowincjonalnym miasteczku. Pragną odmienić swoje życie i wrócić do Moskwy, gdzie się urodziły. To opowieść o marzeniach, rozczarowaniach i ludzkiej tęsknocie.",
    "genre": "dramat",

    },
    {
    "author": "J.R.R. Tolkien",
    "title": "Władca Pierścieni",
    "time_period_of_creation": 1954,
    "language": "polish",
    "publication_year": 1954,
    "publisher": "Wydawnictwo Amber",
    "description": "Władca Pierścieni to epicka saga fantasy, która opowiada o losach hobbita Frodo Bagginsa i jego towarzyszy w ich misji zniszczenia potężnego pierścienia. To historia walki dobra ze złem, pełna przygód, magii i niezapomnianych postaci.",
    "genre": "fantasy",

    },
    {
        "author": "Rafał Ziemkiewicz",
        "title": "Włam się do mózgu. Jak czytać to, co nas omija",
        "time_period_of_creation": 2017,
        "language": "polish",
        "publication_year": 2017,
        "publisher": "Wydawnictwo Fronda",
        "description": "Włam się do mózgu to książka, która zachęca do refleksji i spojrzenia na świat w sposób niekonwencjonalny. Autor, Rafał Ziemkiewicz, przedstawia w niej swoje przemyślenia na temat kultury, polityki i społeczeństwa, skłaniając do głębszego zastanowienia się nad tym, co nas otacza.",
        "genre": "literatura faktu",

    },
    {
        "author": "Tomasz Piątek",
        "title": "Wodogrzmoty Małgorzaty",
        "time_period_of_creation": 2016,
        "language": "polish",
        "publication_year": 2016,
        "publisher": "Wydawnictwo Czarne",
        "description": "Wodogrzmoty Małgorzaty to reportaż, który przedstawia historię Małgorzaty, młodej dziewczyny z biednej rodziny, która zostaje wybrana do udziału w popularnym programie telewizyjnym. Książka porusza tematykę manipulacji mediów i ich wpływu na życie jednostki.",
        "genre": "literatura faktu",

    },
    {
        "author": "Harper Lee",
        "title": "Zabić drozda",
        "time_period_of_creation": 1960,
        "language": "polish",
        "publication_year": 1960,
        "publisher": "Zysk i S-ka",
        "description": "Zabić drozda to amerykańska powieść klasyczna, która ukazuje niesprawiedliwość, rasizm i uprzedzenia w amerykańskim społeczeństwie lat 30. XX wieku. Książka porusza trudne tematy i skłania do refleksji nad ludzką naturą.",
        "genre": "literatura obyczajowa",

    },
    {
        "author": "Franz Kafka",
        "title": "Zamek",
        "time_period_of_creation": 1922,
        "language": "polish",
        "publication_year": 1922,
        "publisher": "Wydawnictwo Literackie",
        "description": "Zamek to powieść, która opowiada historię mężczyzny imieniem K., który przybywa do tajemniczego zamku, aby podjąć pracę jako urzędnik. Jednak napotyka na liczne trudności i niejasności. Książka porusza temat alienacji, biurokracji i niemożności osiągnięcia celu.",
        "genre": "literatura obyczajowa",

    },
    {
        "author": "Fiodor Dostojewski",
        "title": "Zapiski z martwego domu",
        "time_period_of_creation": 1861,
        "language": "polish",
        "publication_year": 1861,
        "publisher": "Wydawnictwo Świat Książki",
        "description": "Zapiski z martwego domu to powieść, która opowiada o życiu więźniów w syberyjskim więzieniu. Autor, Fiodor Dostojewski, przedstawia w niej surowe warunki, jakie panują w więzieniu oraz psychologiczne i moralne dylematy bohaterów.",
        "genre": "literatura obyczajowa",

    },
    {
        "author": "Stephen King",
        "title": "Zielona mila",
        "time_period_of_creation": 1996,
        "language": "polish",
        "publication_year": 1996,
        "publisher": "Albatros",
        "description": "Zielona mila to powieść, której akcja rozgrywa się w więzieniu Cold Mountain Penitentiary. Opowiada historię więźnia Johna Coffeya, który posiada tajemniczą moc uzdrawiania. Książka porusza tematykę sprawiedliwości, ludzkiej natury i nadziei.",
        "genre": "horror",

    },
    {
        "author": "Markus Zusak",
        "title": "Złodziejka książek",
        "time_period_of_creation": 2005,
        "language": "polish",
        "publication_year": 2005,
        "publisher": "Albatros",
        "description": "Złodziejka książek to powieść, która opowiada historię młodej dziewczyny o imieniu Liesel, która kradnie książki w czasie II wojny światowej. Książka porusza tematykę miłości do literatury, odwagi i ludzkiej determinacji.",
        "genre": "literatura obyczajowa",

    },
    {
        "author": "Audrey Niffenegger",
        "title": "Żona podróżnika w czasie",
        "time_period_of_creation": 2003,
        "language": "polish",
        "publication_year": 2003,
        "publisher": "Prószyński i S-ka",
        "description": "Żona podróżnika w czasie to powieść, która opowiada o miłości Clare i Henry'ego. Henry jest podróżnikiem w czasie, który niekontrolowanie przemieszcza się w czasie. Książka porusza tematykę miłości, przeznaczenia i trudności związanych z podróżowaniem w czasie.",
        "genre": "romans",

    },
    {
        "author": "Yann Martel",
        "title": "Życie Pi",
        "time_period_of_creation": 2001,
        "language": "polish",
        "publication_year": 2001,
        "publisher": "Znak",
        "description": "Życie Pi to powieść, która opowiada historię chłopca o imieniu Pi, który ocalał z katastrofy morskiej i znalazł się na łodzi wraz z tygrysem. Książka porusza tematykę przetrwania, wiary i relacji człowieka z dziką naturą.",
        "genre": "przygodowa",
    },
    {
        "author": "Aleksander Fredro",
        "title": "Żywot człowieka poczciwego",
        "time_period_of_creation": 1842,
        "language": "polish",
        "publication_year": 1842,
        "publisher": "Wydawnictwo Literackie",
        "description": "Żywot człowieka poczciwego to komedia autorstwa Aleksandra Fredry. Opowiada o perypetiach i przygodach bohatera, Jana Kantego Czeczota. Książka jest pełna humoru, dowcipów i obrazuje życie szlachty w czasach polskiego romantyzmu.",
        "genre": "komedia",

    },
    {
        "author": "Andrzej Stasiuk",
        "title": "Żywoty równoległe",
        "time_period_of_creation": 1995,
        "language": "polish",
        "publication_year": 1995,
        "publisher": "Czarne",
        "description": "Żywoty równoległe to zbiór esejów napisanych przez Andrzeja Stasiuka. Autor porusza w nich tematykę podróży, ludzi, miejsc i refleksje nad rzeczywistością. Książka zaprasza czytelnika do refleksji i kontemplacji nad światem.",
        "genre": "literatura faktu",
    }
]

def add_books():
    for book_data in books_data:
        book = Books(**book_data)
        book.save()


add_books()
