# Generated by Django 4.2.1 on 2023-05-25 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "time_period_of_creation",
                    models.IntegerField(blank=True, default=2000, max_length=4),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("english", "angielski"), ("polish", "polski")],
                        max_length=40,
                    ),
                ),
                (
                    "publication_year",
                    models.IntegerField(blank=True, default=2000, max_length=4),
                ),
                ("publisher", models.CharField(blank=True, max_length=40)),
                ("description", models.TextField(blank=True, max_length=200)),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("biografy", "biografie"),
                            ("child", "dla dzieci"),
                            ("horror", "horror"),
                            ("reportage", "literatura faktu"),
                            ("common_literature", "literatura obyczajowa"),
                            ("foreign_belles_lettres", " literatura piękna obca"),
                            ("polish_belles_lettres", "literatura piękna polska"),
                            ("romans", "romans"),
                            ("poezja", "poezja"),
                        ],
                        max_length=22,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rental", models.DateField()),
                ("date_return", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applikacja.books",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverDue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_overdue", models.DateField()),
                (
                    "rental",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applikacja.rentalbook",
                    ),
                ),
            ],
        ),
    ]
