# Generated by Django 4.2.1 on 2023-05-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applikacja", "0002_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("rented", "Rented")],
                default="available",
                max_length=20,
            ),
        ),
    ]
